services:
  - type: web
    name: personal-expenses-tracker
    env: static
    buildCommand: |
      # Install Flutter
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter doctor
      flutter config --enable-web
      flutter pub get
      flutter build web --release
    staticPublishPath: build/web
    envVars:
      - key: FLUTTER_VERSION
        value: 3.16.0
